trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'opus-android-build'

steps:
- task: Docker@2
  displayName: Build Opus in image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
