trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'opus-android-build'

steps:
- task: CmdLine@2
  inputs:
    script: |
      set -x
      docker build -t "$(imageName)" .
      docker create --name run "$(imageName)"
      docker cp run:/app/release/android $(Build.ArtifactStagingDirectory)
    workingDirectory: 'android'
- task: UniversalPackages@1
  displayName: Universal Publish
  inputs:
    command: publish
    publishDirectory: $(Build.ArtifactStagingDirectory)
    vstsFeedPublish: android
    vstsFeedPackagePublish: opus
    packagePublishDescription: Opus Android build
