trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'opus-android-build'

steps:
- task: Docker@2
  displayName: Build Opus in image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: android/Dockerfile
- task: CmdLine@2
  inputs:
    script: |
      docker build -t "$(imageName)" .
      docker run -a stdout -a stderr --rm "$(imageName)" ls
    workingDirectory: 'android'