trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'opus-android-build'

steps:
- task: CmdLine@2
  inputs:
    script: |
      set -x
      docker build -t "$(imageName)" .
      docker create --name run "$(imageName)"
      docker cp run:/app/release/android $(Build.ArtifactStagingDirectory)
    workingDirectory: 'android'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: opus-android
