trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'opus-android-build'

steps:
- task: CmdLine@2
  inputs:
    script: |
      set -x
      docker build -t "$(imageName)" .
      docker create --name run "$(imageName)"
      docker cp run:/app/release/android $(Build.ArtifactStagingDirectory)
    workingDirectory: 'android'
- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'fb657c90-eea3-428b-9b08-6f664431fe4e/2816835e-4087-4c88-9830-d190d2a9ac5c'
    vstsFeedPackagePublish: 'opus-android'
    versionOption: 'custom'
    versionPublish: '1.3.1'
    verbosity: 'Trace'
