trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'opus-android-build'

steps:
- task: CmdLine@2
  inputs:
    script: |
      set -x
      docker build -t "$(imageName)" .
      docker create --name run opus-build
      docker cp run:/app/release/opus-android.tar.gz ./
    workingDirectory: 'android'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: android/opus-android.tar.gz
    artifactName: opus-android
